### ISSUE TITLE
Error running helm install

### ISSUE THREAD

**Issue by angad012** [AjayTripathy/kubemetrics-quickstart#1]
I am running the charts in an existing cluster setup and get this error 
 $ helm install --dry-run cost-analyzer --name cost-analyzer --namespace monitoring

Error: failed to download "cost-analyzer"

**Comment by AjayTripathy** [comment]
Hi angad012, cost-analyzer is supplied locally, not downloaded from any helm repository (yet). Can you try navigating to the kubecost-quickstart home directory and running this same command from there? If that still doesn't work, can you supply some more details by running 

helm install --debug --dry-run cost-analyzer --name cost-analyzer --namespace monitoring

**Comment by angad012** [comment]
Hi i have done the same as you described in my issue! Please have a look!

**Comment by angad012** [comment]
Hi Ajay

I did the same and posted the issue on github. Gives the same error!

ANGAD KUMAR | PROJECT MANAGER
Bergstraße 49, 69469 Weinheim, Germany

LET’S CONNECT…
Mobile: +49 17626834180
LinkedIn: linkedin.com/in/angad-kumar-573a5835<https://www.linkedin.com/in/angad-kumar-573a5835>
[/Users/angad.kumar/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_1740791813]

Blockchain Designed for Business

**Comment by AjayTripathy** [comment]
The following works for me:

> git clone https://github.com/AjayTripathy/kubecost-quickstart.git
> cd kubecost-quickstart
> helm install --debug --dry-run cost-analyzer --name cost-analyzer --namespace monitoring
> 

Running from the directory below, cost-analyzer, does give the error you described:

> Ajays-MBP-2:cost-analyzer atripathy$ pwd
> /Users/atripathy/kubecost-quickstart/cost-analyzer
> Ajays-MBP-2:cost-analyzer atripathy$ helm install --dry-run cost-analyzer --name cost-analyzer --namespace monitoring
> Error: failed to download "cost-analyzer" (hint: running `helm repo update` may help)

However, this is not the right place to run it from. If you are experiencing the error from the home directory, can you please supply your helm version as well as the full output of 

> helm install --debug --dry-run cost-analyzer --name cost-analyzer --namespace monitoring 

Additionally, you can also try running

> helm repo update

Though I'm not sure that will help in this case, as helm should first check the folder you are running it from for a folder whose name matches the install name, containing a chart.yaml file before going to the repo.

**Comment by angad012** [comment]
Thanks! this works. I have issues accessing the dashboard after port forwarding. Trying to look at why but any ideas why are welcome. 

I also get this error when directly using this command from the readme. Although can be usually found from the console UI. 
$ kubectl port-forward --namespace monitoring deployment/cost-analyzer-grafana 3000

error: invalid resource name "deployment/cost-analyzer-grafana": [may not contain '/']

**Comment by dwbrown2** [comment]
Let's close this because the project is deprecated in favor of Kubecost models. Reach out to team@kubecost.com if you still need help.
