### ISSUE TITLE
Persistent Volume Claims status is stuck in pending status

### ISSUE THREAD

**Issue by gokcesurenkok** [AjayTripathy/kubemetrics-quickstart#2]
Hi, 

I am trying to install kubecost on my k8s cluster , but when i applied 
`helm install cost-analyzer --name cost-analyzer --namespace monitoring`

The persistent volume claims named as 
cost-analyzer-prometheus-alertmanager
cost-analyzer-prometheus-server 
 are stuck in Pending status , so prometheus server itself is having problem to run.

**Comment by dwbrown2** [comment]
Hey, is your cluster on AWS/EKS? If so, I suspect that this may have to do with provisioning storage if you are running on a new cluster. Specifically, you may have to set your default StorageClass: https://docs.aws.amazon.com/eks/latest/userguide/storage-classes.html

I believe the best starting points for investigating are 1) reviewing general event logs (kubectl get events --namespace=monitoring) and 2) looking at the individual pods (kubectl describe pod --namespace=monitoring [POD NAME]). The Prometheus server pod is what you would want to investigate. Can you share what you find there and we can give more targeted advice?

**Comment by gokcesurenkok** [comment]
thanks for your quick reply, and sorry for my late response. 
i have tried to use it for my on-prem k8s cluster on vms (because we want to have an idea how much it would cost us to migrate an on-prem cluster to  google cloud) , but had this issue 
i have added node exporter and rest of the necessary exporters needed for my existing prometheus to scrape without using your helm charts 
thanks for your attention 
it works ok now
